language: python

stages:
  - lint
  - test
  - name: publish
    if: tag =~ ^\d+\.\d+\.\d+$

install:
  - pip install tox

jobs:
  include:
    - python: 2.7
      stage: test
      script: tox -e py27

    - python: 3.6
      stage: test
      script: tox -e py36

    - stage: publish
      script: skip
      python: 2.7
      deploy:
        provider: pypi
        user: flyte
        password:
          secure: "eSedXSEOXM+YGl+zQUjDg2EGhTIHfiMBn2Bcrx5Gyinx19Z9vaL/oy6wUw+0bpA3hztQZzgFwxxgAlEvvp9xoWknR+9AWUYlmmruWrZMcnxWG6d+kTmLehQ+xetObgqszZorVC/WmvvL7t6Tuyh/DHZZ3nw5T817jOg243eXVaQr53UFL20879I7elnRc1gGZOz9GuFMJRhGqX3D3tgseR3sKI7IYSOLNVYfJGN9FVdbn8qMcdb6Q8Ecb1RtmmK5p3uBTFe0rSZrhBD3gWjxFrpojSSsrve/duxHkY0c5ZQkv3uihFLzyLh7a8r8HW8sC7uej+HOr989Y9I6So86BHcqynKIZjrXknEsffAeCf/81hrr6Q4hiwNi+d3adnDWz2SwfYF9LvPRYJLguyKSHdjkKp8OJcJedi9rdF6CxX1Tz5RqndZLUkJH4Eybsjf65xJ4KnSbFKizESGzA9ecwCddp39lUt87bto9pZ9uXpxkKm5PLYJVxint1F1Y3C4yq5zDcRsv2J7GKFVsvfkd++N3NMaTm80bxo2sJnw0xoLr3nokzHICkgr5aUuxipYiDt0tiI3xV7k0jRqQM2dsY5Dqq31Sz7CRHVg9JaBcRe58FMrKsKnBisPbzCpAX8xbR/eXo+Y+CIi3ABf9txMz+qft8/LXEJGel2J0srOZCcQ="
        on:
          tags: true
          repo: flyte/pi-mqtt-gpio
        distributions: bdist_wheel

    - stage: publish
      python: 3.6
      script: skip
      deploy:
        provider: pypi
        user: flyte
        password:
          secure: "eSedXSEOXM+YGl+zQUjDg2EGhTIHfiMBn2Bcrx5Gyinx19Z9vaL/oy6wUw+0bpA3hztQZzgFwxxgAlEvvp9xoWknR+9AWUYlmmruWrZMcnxWG6d+kTmLehQ+xetObgqszZorVC/WmvvL7t6Tuyh/DHZZ3nw5T817jOg243eXVaQr53UFL20879I7elnRc1gGZOz9GuFMJRhGqX3D3tgseR3sKI7IYSOLNVYfJGN9FVdbn8qMcdb6Q8Ecb1RtmmK5p3uBTFe0rSZrhBD3gWjxFrpojSSsrve/duxHkY0c5ZQkv3uihFLzyLh7a8r8HW8sC7uej+HOr989Y9I6So86BHcqynKIZjrXknEsffAeCf/81hrr6Q4hiwNi+d3adnDWz2SwfYF9LvPRYJLguyKSHdjkKp8OJcJedi9rdF6CxX1Tz5RqndZLUkJH4Eybsjf65xJ4KnSbFKizESGzA9ecwCddp39lUt87bto9pZ9uXpxkKm5PLYJVxint1F1Y3C4yq5zDcRsv2J7GKFVsvfkd++N3NMaTm80bxo2sJnw0xoLr3nokzHICkgr5aUuxipYiDt0tiI3xV7k0jRqQM2dsY5Dqq31Sz7CRHVg9JaBcRe58FMrKsKnBisPbzCpAX8xbR/eXo+Y+CIi3ABf9txMz+qft8/LXEJGel2J0srOZCcQ="
        on:
          tags: true
          repo: flyte/pi-mqtt-gpio
        distributions: sdist bdist_wheel
